name: Node.js CI

on: [push]

permissions:
  contents: read

jobs:
  unit-test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: npm ci

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
